import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderCom from "@/components/Header/Header";
import getData from "@/lib/getData";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout  ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let loginStatus = false ;
  const profileData = await getData('user_data/')

  if(profileData?.data?.email)
  {
    loginStatus = true
  }
  return (
    <html lang="en">
      <body className={inter.className}>
      <HeaderCom loginStatus={loginStatus}/>
        {children}
        </body>
    </html>
  );
}
