import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderCom from "@/components/Header/Header";
import getData from "@/lib/getData";
import NextTopLoader from "nextjs-toploader";
import { Suspense } from "react";
import Loading from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout  ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let loginStatus = false ;
  const profileData = await getData('user_data/')

  if(profileData?.data?.email)
  {
    loginStatus = true
  }
  return (
    <html lang="en">
      <body className={inter.className}>
      <Suspense fallback ={<Loading/>}>
        <NextTopLoader color='rgb(29 78 216 )' showSpinner= {false} height={2} shadow={false} />
      <HeaderCom loginStatus={loginStatus}/>
        {children}
        </Suspense>
        </body>
    </html>
  );
}
